repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint --fail-under=8.0
        language: system
        types: [python]